label_image: bitmap_helpers.cc label_image.cc
	g++ -O3 -std=c++11 -march=native label_image.cc bitmap_helpers.cc -o label_image -I../../../../../ -I../../downloads/flatbuffers/include -ldl -lpthread ../../gen/lib/rpi_armv7/libtensorflow-lite.a
